blank_issues_enabled: false
contact_links:
  - name: Request user membership to the public bcgov GitHub org and access to create a public GitHub repo
    url: https://developer.gov.bc.ca/docs/default/component/bc-developer-guide/use-github-in-bcgov/bc-government-organizations-in-github/#directions-to-sign-up-and-link-your-account-for-bcgov
    about: You can now join the public bcgov GitHub org on your own. More info at the link!
  - name: Request user membership to the private bcgov-c GitHub org
    url: https://developer.gov.bc.ca/docs/default/component/bc-developer-guide/use-github-in-bcgov/bc-government-organizations-in-github/#directions-to-sign-up-and-link-your-account-for-bcgov-c
    about: You can now join the private bcgov-c GitHub org on your own. More info at the link!
  - name: Request for a private repository in the bcgov-c GitHub organization
    url: https://citz-do.atlassian.net/servicedesk/customer/portal/2/group/9/create/60
    about: Please submit a request using the link above to make your request for a private repository in the bcgov-c GitHub organization.
  - name: Reclaim a repository with no admin
    url: https://citz-do.atlassian.net/servicedesk/customer/portal/2/group/9/create/22
    about: If you require access to a GitHub repository that has no administrators in a BC gov-managed GitHub organization, please submit a request via the link above.
  - name: Request to have a GitHub Application added to a repository in a BC gov-managed GitHub organization
    url: https://citz-do.atlassian.net/servicedesk/customer/portal/2/group/9/create/10
    about: Please submit a request using the link above to request having a GitHub Application added to a repository within a BC gov-managed GitHub organization.
  - name: Request to transfer repo into bcgov-c
    url: https://citz-do.atlassian.net/servicedesk/customer/portal/2/group/9/create/294
    about: Please submit a request using the link above to request transferring a repository into the bcgov-c GitHub organization.
  - name: OCP4 Project Set Requests, Annotation Updates, and Quota Changes.
    url: https://registry.developer.gov.bc.ca
    about: All of these tasks are now performed in the Project Registry - make sure to update your bookmarks!
  - name: Request access to RocketChat
    url: https://developer.gov.bc.ca/docs/default/component/bc-developer-guide/rocketchat/steps-to-join-rocketchat/
    about: Did you know that most employees and contractors don't need to an invite to join Rocketchat? You can log straight in! More info at the link!
  - name: Request for an Pathfinder SSO Client in a standard realm
    url: https://bcgov.github.io/sso-requests/
    about: To create a set of Pathfinder SSO clients (in KeyCloak DEV, TEST, PROD).
  - name: Get support
    url: https://digital.gov.bc.ca/cloud/services/private/support/
    about: View different support resources and channels.
